config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "my_registrations" }

  resources :users do
    resources :posts
  end

  resources :comments
  resources :post_likes, only: [:new, :create]
  resources :comment_likes, only: [:new, :create]
  resources :friendships, only: [:create, :destroy]
  resources :friend_requests, only: [:create, :destroy]
  get '/sent_friend_requests', to: 'friend_requests#sent_requests'
  get '/received_friend_requests', to: 'friend_requests#received_requests'
  get '/friends', to: 'friendships#friends'
  get 'myprofile', to: 'users#my_profile'
  root 'users#index'


end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates_integrity_of  :image
  validates_processing_of :image

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook]


  has_many :authored_posts, class_name: 'Post', foreign_key: 'author_id', :dependent => :destroy
  #posts they have written
  has_many :authored_comments, class_name: 'Comment', foreign_key: 'author_id', :dependent => :destroy
  #retuns the comments they wrote
  has_many :post_likes, :dependent => :destroy
  #returns the number of posts they like
  has_many :liked_posts, through: 'post_likes', source: 'post'
  #returns the actual posts they like.
  has_many :comment_likes
  has_many :liked_comments, through: 'comment_likes', source: 'comment'
  #Friend Requests
  #returns all the requests a user has sent
  has_many :issued_requests, class_name: "FriendRequest", foreign_key: "requester_id", :dependent => :destroy
  #returns all the requests a user has recieved
  has_many :received_requests, class_name: "FriendRequest", foreign_key: "requested_id", :dependent => :destroy
  #returns the names of the users a user wants to be friend with
  has_many :pending_friendees, through: :issued_requests, source: :requested
  #returns the names of the people who have requested friendships
  has_many :pending_frienders, through: :received_requests, source: :requester
  #Friendships
  has_many :friendships, foreign_key: 'friender_id', :dependent => :destroy
  has_many :friends, through: :friendships, source: :friendee
  default_scope -> { order(name: :asc) }

  def friends?(user)
    self.friends.include?(user)
  end

  def received_request_pending?(user)
    self.pending_frienders.include?(user)
  end

  def notifactions?
    pending_frienders.count
  end

  def sent_request_pending?(user)
    self.pending_friendees.include?(user)
  end

  def is?(user)
    true if self==user
  end
  private
    def image_size_validation
      errors[image] << "should be less than 500KB" if image.size > 0.5.megabytes
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :friends?, only: :show


  def index
    @users=User.all
    @friend_request=FriendRequest.new
    @friendship=Friendship.new
  end

  def show
    @user=User.find(params[:id])

    @posts=@user.authored_posts
    @post_like=PostLike.new
  end

  def update
    @user=current_user
    if @user.update_attributes(user_params)
      flash[:success]="Successfully updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def my_profile
    @post=Post.new
    @user=current_user
    @posts=@user.authored_posts
  end

  private
  def friends?
    @user=User.find(params[:id])
    unless current_user.friends.include?(@user)
      flash[:danger]="You must be friends to view someones profile."
      redirect_to(users_url)
    end
  end

  def user_params
    params.require(:user).permit(:image, :image_cache, :remove_image)
  end

end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/_image_upload.html.erb
<%= form_for(@user) do |f| %>
  <div class="field">
    <%= f.label :Update_photo %></br>
    <%= f.file_field :image %></br>
  </div>
  <div class="actions">
    <%= f.submit "Change Photo" %></br>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>All Users</h1>

<% @users.each do |user| %>
<div class="index">
  <%= image_tag user.image.url %>
  <p><%= link_to user.name, user_path(user) %></p>
  <% if current_user.is?(user) %>
    <%= link_to "My Profile", myprofile_path %>

  <% elsif current_user.received_request_pending?(user) %>
    <%= render 'friendships/form',  :locals => {:requester_id => user.id} %>
  <% elsif current_user.sent_request_pending?(user) %>

    <%= "Friend request pending." %>
  <% elsif current_user.friends?(user) %>
    <%= render 'friendships/unfriend', :locals => {:friendee_id => user.id} %>
  <% else %>
    <%= render 'friend_requests/form', :locals => {:requested_id => user.id} %>
  <% end %>
</div>
</br>
<% end %>

app/views/users/my_profile.html.erb
<h1>Welcome <%= @user.name %> </h1>
<%= link_to "Edit Profile", edit_user_registration_path(@user)  %>
<p>
  <%= image_tag @user.image.url %>
</p>
<%= render 'users/image_upload' %>

<%= render 'posts/form' %>

<% @posts.each do |post| %>
  <div class="posts">
  <p><%= post.content %></p>
  <%= "Likes: #{post.likes.count}" %></br>
  <p>Posted <%= time_ago_in_words(post.created_at) %> ago.</p>
  </div>
</br>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<p>
  <%= image_tag @user.image.url  %>
</p>


<% @posts.each do |post| %>
  <div class="posts">
  <p><%= post.content %></p>
  <%= render 'post_likes/form', :locals => {:post_id => post.id} unless post.liked?(current_user) %>
  <%= "Likes: #{post.likes.count}" %></br>
<p>Posted <%= time_ago_in_words(post.created_at) %> ago.</p>
  </div>
</br>
<% end %>