config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "my_registrations" }

  resources :users do
    resources :posts
  end

  resources :comments
  resources :post_likes, only: [:new, :create]
  resources :comment_likes, only: [:new, :create]
  resources :friendships, only: [:create, :destroy]
  resources :friend_requests, only: [:create, :destroy]
  get '/sent_friend_requests', to: 'friend_requests#sent_requests'
  get '/received_friend_requests', to: 'friend_requests#received_requests'
  get '/friends', to: 'friendships#friends'
  get 'myprofile', to: 'users#my_profile'
  root 'users#index'


end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :friender, class_name: "User"
  belongs_to :friendee, class_name: "User"
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :authenticate_user!
  def friends
    @friends=current_user.friends
  end

  def create

    @friend_request=FriendRequest.where("requester_id = ? AND requested_id = ?", params[:friendship][:requester_id], current_user.id).first
    if @friend_request
      Friendship.create(friender_id: params[:friendship][:requester_id], friendee_id:current_user.id)
      Friendship.create(friender_id: current_user.id, friendee_id: params[:friendship][:requester_id])
      @friend_request.destroy
      flash[:success]="Friendship made!"
      redirect_to received_friend_requests_path
    else
      flash.now[:danger]="Unable to make friendship"
    end
  end

    def destroy
      @friendship=Friendship.find(params[:id])
      @friendship2=Friendship.where("friender_id = ? AND friendee_id = ?",  params[:friendship][:friendee_id], current_user.id).first
      @friendship.destroy
      @friendship2.destroy
      redirect_to users_url
    end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_form.html.erb
<%= form_for(@friendship) do |f| %>
  <%= f.hidden_field :requester_id, value: local_assigns[:locals][:requester_id] %>
<%= f.submit "Accept Request" %>
<% end %>

app/views/friendships/_unfriend.html.erb
<%= form_for(current_user.friendships.find_by(friendee_id: local_assigns[:locals][:friendee_id]),
             html: { method: :delete }) do |f| %>
  <%= f.hidden_field :friendee_id, value: local_assigns[:locals][:friendee_id] %>
  <%= f.submit "Unfriend", class: "btn" %>
<% end %>

app/views/friendships/friends.html.erb
<h1>Friends</h1>
<% if !@friends.empty? %>
  <% @friends.each do |friend| %>
  <%= image_tag friend.image.url %>
    <p><%= link_to friend.name, user_path(friend) %></p>
    <% end %>
  <% else %>
  <p>To find people you might know go to <%= link_to "All users", users_path %>
<% end %>