config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "my_registrations" }

  resources :users do
    resources :posts
  end

  resources :comments
  resources :post_likes, only: [:new, :create]
  resources :comment_likes, only: [:new, :create]
  resources :friendships, only: [:create, :destroy]
  resources :friend_requests, only: [:create, :destroy]
  get '/sent_friend_requests', to: 'friend_requests#sent_requests'
  get '/received_friend_requests', to: 'friend_requests#received_requests'
  get '/friends', to: 'friendships#friends'
  get 'myprofile', to: 'users#my_profile'
  root 'users#index'


end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  #post.author= author
  has_many :comments, :dependent => :destroy
  #post.comments- all the comments
  has_many :likes, class_name: 'PostLike', :dependent => :destroy
  #post.likes- number of likes
  has_many :likers, through: 'likes', source: 'user'
  #post.likers=users how liked it
  default_scope -> { order(created_at: :desc) }

  def liked?(user)
    likers.include?(user)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  def new
    @post=Post.new
  end

  def create
    @post=current_user.authored_posts.build(post_params)
    redirect_to user_posts_path if @post.save
  end

  def show
    @post=Post.find(params[:id])
    @comment=Comment.new
    @comments=@post.comments
    @post_like=PostLike.new
    @comment_like=CommentLike.new

  end

  def index
    @post=Post.new
    @post_like=PostLike.new
    friend_ids = "SELECT friendee_id FROM friendships
                     WHERE  friender_id = :user_id"
    @posts= Post.where("author_id IN (#{friend_ids})
                     OR author_id = :user_id", user_id: current_user.id)

  end

  def destroy
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post, url: user_posts_url(current_user)) do |f| %>
  <%= f.text_area :content, size: "60x6", placeholder: 'I...' %></br>
<%= f.submit "Post" %>
<% end %>

app/views/posts/index.html.erb
<h2>What's on your mind?</h2>
<%= render 'posts/form' %>
<h2>Recent posts</h2>


<% @posts.each do |post| %>
  <div class="posts">
<%= link_to user_post_path(post.author, post) do %>
  <%= image_tag post.author.image.url  %>
  <p><%= post.content %></p>
  <%= "Likes: #{post.likes.count}" %></br>
  <p><%= post.author.name  %></p>
  <p>Posted <%= time_ago_in_words(post.created_at) %> ago.</p>
<% end %>
<%= render 'post_likes/form', :locals => {:post_id => post.id} unless post.liked?(current_user) %>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1>What's on your mind...</h1>
<%= render 'posts/form' %>

app/views/posts/show.html.erb
<h1>Post</h1>
<div class="posts">
  <%= image_tag @post.author.image.url  %>
  <%= @post.author.name %></br>
  <%= @post.content %></br>
  <p>Posted <%= time_ago_in_words(@post.created_at) %> ago.</p>
  <%= "Number of Likes: #{@post.likes.count}" %>
<%= render 'post_likes/form', :locals => {:post_id => @post.id} unless @post.liked?(current_user) %>

</div>

<%= render 'comments/form' %>
<h2>Comments</h2>
<% if !@comments.empty? %>

    <% @comments.each do |comment| %>
  <div class="comments">
    <%= image_tag comment.author.image.url  %></br>
    <%= link_to comment.author.name, comment.author %> says...
    <%= comment.content %></br>
    <%= "Number of Likes: #{comment.likes.count}" %>
    <p>Commented <%= time_ago_in_words(comment.created_at) %> ago.</p>
    <%= render 'comment_likes/form', :locals => {:comment_id => comment.id} unless comment.liked?(current_user) %>
  </div></br>
    <% end %>

<% end %>